name: 下载
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: 下载文件
      run: |
        mkdir download
        cd download
        ./b 'https://www.mediafire.com/file/puugmt9ek9dxyey/macos_Mojave_vmdk_10.14.6.vmdk'
    - name: 上传文件
      uses: actions/upload-artifact@main
      with:
        name: mojave.vmdk
        path: ./download/
