name: 下载
on:
  gollum
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: 下载文件
      run: |
        mkdir download
        cd download
        wget -c https://download852.mediafire.com/kvsxa96cv2sg/puugmt9ek9dxyey/macos+Mojave+vmdk+10.14.6.vmdk
    - name: 上传文件
      run: |
        curl -sL https://git.io/file-transfer | sh
        ./transfer trs ./download/
