name: 填报体温
on: 
  schedule:
    - cron: '10 0 * * *'
    - cron: '20 3 * * *'
    - cron: '30 6 * * *'
    - cron: '5 9 * * *'
  push:
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: 运行
      run: |
        chmod 777 daily_health_reqwest
        ./daily_health_reqwest
      
