name: health
on: 
  schedule:
    - cron: '45 22 * * *'
    - cron: '10 01 * * *'
#     - cron: '20 3 * * *'
    - cron: '30 5 * * *'
    - cron: '5 8 * * *'
  push:
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: run
      run: |
        chmod 777 dhr
        ./dhr ${{ secrets.NUM }}
      
