name: 填报体温
on: 
  schedule:
    - cron: '10 23 * * *'
    - cron: '20 3 * * *'
    - cron: '30 5 * * *'
    - cron: '5 9 * * *'
jobs:
  downloading:
    runs-on: ubuntu-latest
    steps:
    - name: Check out Git repository
      uses: actions/checkout@v2
    - name: 运行
      run: |
        chmod 777 daily_health_reqwest
        ./daily_health_reqwest
      
